// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Jetzt kontaktieren
	 */
	contact_button: string
	/**
	 * kostenlos Angebot anfordern
	 */
	contact_button_offer: string
	index: {
		/**
		 * Startseite
		 */
		title: string
		/**
		 * Dein Auftrag ist unser Antrieb!
		 */
		heading: string
		/**
		 * NEKO ist Dein kompetenter und zuverlässiger Full-Service-Partner im Bereich Veranstaltungstechnik und -management.
		 */
		subheading: string
		/**
		 * /img/index/webp/hero.webp
		 */
		img_hero: string
		examples: {
			events: {
				/**
				 * Events
				 */
				title: string
				/**
				 * Jede Veranstaltung ist einmalig
				 */
				subtitle: string
				/**
				 * NEKO stattet Dein Event mit qualitativer und fortschrittlicher Technik aus. Durch exzellente Beratung, fachgerechte Planung sowie professionelle Umsetzung sorgen wir dafür, dass Deine Veranstaltung unvergesslich wird!
				 */
				text: string
				/**
				 * /img/index/webp/events.webp
				 */
				img: string
			}
			exhibitions: {
				/**
				 * Messen & Aussteller
				 */
				title: string
				/**
				 * Überlass nichts dem Zufall
				 */
				subtitle: string
				/**
				 * Wir meistern alle technischen und logistischen Herausforderungen Deines Messeauftritts. Mit Ideenreichtum und jahrelanger Erfahrung im Messe- und Standbau sorgen wir für individuelle und einmalige Messepräsenz.
				 */
				text: string
				/**
				 * /img/index/webp/exhibitions.webp
				 */
				img: string
			}
			seminars: {
				/**
				 * Kongresse & Seminare
				 */
				title: string
				/**
				 * Im großen oder kleinen Stil
				 */
				subtitle: string
				/**
				 * Mit modernster Konferenz- und Medientechnik und unserem Full-Service-Ansatz übernehmen wir die Konzeption Deines Business-Programms und sorgen für einen reibungslosen Ablauf.
				 */
				text: string
				/**
				 * /img/index/webp/seminars.webp
				 */
				img: string
			}
			hotels: {
				/**
				 * Hotels
				 */
				title: string
				/**
				 * Event- und Treffpunkt
				 */
				subtitle: string
				/**
				 * Ob Geschäftsmeeting, Hochzeit oder privates Fest – mit unserem Know-how beraten wir Dich bei der Auswahl des richtigen Veranstaltungsequipments und setzen Dein Hotel-Event perfekt ins Szene.
				 */
				text: string
				/**
				 * /img/index/webp/hotels.webp
				 */
				img: string
			}
		}
	}
	about: {
		/**
		 * Über uns
		 */
		title: string
		/**
		 * Erfahren. Persönlich. Vielseitig. Servicestark.
		 */
		heading: string
		/**
		 * Unsere Leitsätze für Deinen Erfolg!
		 */
		subheading: string
		/**
		 * /img/about/webp/hero.webp
		 */
		img_hero: string
		texts: {
			experienced: {
				/**
				 * Erfahren.
				 */
				title: string
				/**
				 * Seit mehr als 10 Jahren gestalten und inszenieren wir unvergessliche Events und Veranstaltungen mit professionellem Equipment und solidem Know-how.
				 */
				text_card: string
				/**
				 * NEKO versteht sich als technischer Allround-Dienstleister mit individuellen Lösungsansätzen in den Segmenten Ton-, Licht-, Video-, Präsentationstechnik sowie Bühnenbau. Wir bieten eine breitgefächerte Palette an Equipment und Service für Veranstaltungen jeder Dimension an.
				 */
				text: string
				/**
				 * /img/about/webp/experienced.webp
				 */
				img: string
			}
			personal: {
				/**
				 * Persönlich.
				 */
				title: string
				/**
				 * Gerne empfangen wir Dich zu einem unverbindlichen Gespräch in unserem Showroom in Mönchengladbach, wo Du Dich vom professionellen Equipment aus hauseigenem Technikbestand überzeugen kannst.
				 */
				text_card: string
				/**
				 * Ob Du auf einzelne Bereiche der Eventtechnik zurückgreifen möchtest, den ganzheitlichen Allround-Ansatz bevorzugst oder Dein eigenes Equipment in Reparatur geben möchtest – nimm jetzt unverbindlich Kontakt mit uns auf.
				 */
				text: string
				/**
				 * /img/about/webp/personal.webp
				 */
				img: string
			}
			diverse: {
				/**
				 * Vielfältig.
				 */
				title: string
				/**
				 * Konzert, Gala, Tagung, Konferenz, Präsentation oder Messeauftritt. Was steht als nächstes auf Deiner Agenda? Als Partner haben wir unsere Leistungspalette an die allseitigen Herausforderungen unterschiedlichster Szenarien angepasst.
				 */
				text_card: string
				/**
				 * Mit unserem professionellen Netzwerk aus Kooperationspartnern planen und realisieren wir lokale und internationale Events. Dabei geben wir uns mit 08/15-Lösungen genauso wenig zufrieden wie unsere Kunden. Aus Deinen Ideen und Vorstellungen kreieren wir innovative, maßgeschneiderte Konzepte und inszenieren stimmungsvolle, unvergessliche Events.
				 */
				text: string
				/**
				 * /img/about/webp/diverse.webp
				 */
				img: string
			}
			servicestrong: {
				/**
				 * Servicestark.
				 */
				title: string
				/**
				 * Bei uns bekommst Du nicht nur hochwertiges Equipment, sondern auf Wunsch auch Beratungs- und Serviceleistungen wie Unterstützung bei der Eventplanunglanung, Aufbau, Installation, Reparatur und vieles mehr.
				 */
				text_card: string
				/**
				 * Unser Team aus Toningeneuren, Informatikern, Bühnen- & Veranstaltungstechnikern, Licht- & Videooperatoren, Technischen Planern und Bühnenhelfern berät Dich bei sämtlichen Herausforderungen. Stets kompetent, budgetorientiert und technisch versiert! Ob regional oder international, groß oder klein – Dein Auftrag ist unser Antrieb!
				 */
				text: string
				/**
				 * /img/about/webp/servicestrong.webp
				 */
				img: string
			}
		}
	}
	services: {
		/**
		 * Leistungen
		 */
		title: string
		/**
		 * mehr erfahren
		 */
		more_button: string
		/**
		 * Produktpalette
		 */
		products_title: string
		all: {
			sound: {
				/**
				 * Tontechnik
				 */
				title: string
				/**
				 * Wir sorgen für guten Ton!
				 */
				subtitle: string
				/**
				 * NEKO liefert optimale Beschallung, egal welche technischen Herausforderungen der Veranstaltungsort mit sich bringen mag.
				 */
				teaser: string
				/**
				 * Ob Tagungen, Hotels oder Konzerthallen – die technischen und örtlichen Gegebenheiten sind in jeder Location unterschiedlich und beeinflussen die Klangqualität in entscheidendem Maße. Sauberer Klang ist eine unabdingbare Komponente für den Erfolg Deiner Veranstaltung. NEKO liefert die optimale Beschallung, egal welche Herausforderungen der Veranstaltungsort mit sich bringen mag.
				 */
				par1: string
				/**
				 * Zusammen machen wir einen Plan und stellen Dir ausgezeichnetes Equipment von namhaften Herstellern zur Verfügung. Darüber hinaus installieren wir die Technik und führen die Veranstaltung fachlich versiert und Deinen Erwartungen entsprechend durch. Es kommen ausschließlich aufeinander abgestimmte Soundsysteme, moderne Mikrophone und leistungsfähige Peripheriegeräte zum Einsatz.
				 */
				par2: string
				bullets: {
					/**
					 * Aktive und Passive Lautsprecher
					 */
					'0': string
					/**
					 * Endstufen und Soundmanager
					 */
					'1': string
					/**
					 * Kabel- und Funkmikrofone
					 */
					'2': string
					/**
					 * Mischpulte und Monitore
					 */
					'3': string
					/**
					 * DJ Technik
					 */
					'4': string
				}
				/**
				 * Spüre mit uns die ganze Kraft des Klanges!
				 */
				quote: string
				/**
				 * /img/services/webp/sound_card.webp
				 */
				img_card: string
				/**
				 * /img/services/webp/sound_hero.webp
				 */
				img_hero: string
			}
			light: {
				/**
				 * Lichttechnik
				 */
				title: string
				/**
				 * Wir bringen Licht ins Dunkel!
				 */
				subtitle: string
				/**
				 * Bewegtes Licht, LED oder beides? Bühne, Show oder Messestand? Licht ist Pflicht!
				 */
				teaser: string
				/**
				 * Bewegtes Licht, LED oder beides? Bühne, Show oder Messestand? Eins steht fest: Licht ist Pflicht und Du hast die Wahl! NEKO hat einen außergewöhnlich breiten Lichttechnik-Park, der keinen Deiner Wünsche offen lässt. Verzaubere Dein Publikum und profitiere von modernen, spektakulären Lichteffekten.
				 */
				par1: string
				/**
				 * Keine Komponente der Veranstaltungstechnik berührt so sehr wie das Lichtdesign. Es ist ein Gestaltungsmittel, welches Räume in eine beeindruckende Atmosphäre rückt und wirkungsvolle Stimmungen erzeugt. Unsere Lichtdesigner wissen, wie man dieses Mittel gekonnt einsetzt und entwickeln ein überzeugendes Lichtkonzept, das Deinen Räumen Charakter verleiht. Wir beraten Dich bei der Auswahl und bieten Dir Dein ganz individuelles Lichtspektakel.
				 */
				par2: string
				bullets: {
					/**
					 * Kunst- und Tageslichtscheinwerfer
					 */
					'0': string
					/**
					 * LED Scheinwerfer und LED Panels
					 */
					'1': string
					/**
					 * Movinglights und Followspots
					 */
					'2': string
					/**
					 * Profilscheinwerfer und Outdoorstrahler
					 */
					'3': string
					/**
					 * Farbwechsler und Nebelgeräte
					 */
					'4': string
					/**
					 * Lichtsteuerungen, Dimmer und Switches
					 */
					'5': string
					/**
					 * Stromverteilungen und -generatoren
					 */
					'6': string
					/**
					 * Traversen und Lichtstative
					 */
					'7': string
				}
				/**
				 * Erst ein gekonnt inszeniertes Lichtdesign macht aus Deinem Event ein Highlight.
				 */
				quote: string
				/**
				 * /img/services/webp/light_card.webp
				 */
				img_card: string
				/**
				 * /img/services/webp/light_hero.webp
				 */
				img_hero: string
			}
			video: {
				/**
				 * Videotechnik
				 */
				title: string
				/**
				 * Wir bringen Deine Bilder in Bewegung!
				 */
				subtitle: string
				/**
				 * Animationen, Imagefilme, Präsentationscharts oder Grafiken - mit uns gibst Du immer ein gutes Bild ab.
				 */
				teaser: string
				/**
				 * Durch ein reibungsloses Zusammenspiel von Bild und Ton hinterlässt Du bei Deinen Zuschauern einen bleibenden Eindruck. Eine visuelle Untermalung verleiht dem Gesagten mehr Ausdruck, fokussiert die Sinne der Zuschauer auf die Kernbotschaften des Vortrags und hebt diese eindrucksvoll und nachhaltig hervor.
				 */
				par1: string
				/**
				 * Wir bringen unsere ganze Erfahrung mit der medientechnischen Umsetzung von Vorträgen, Reportagen und Live-Übertragungen in Deinen Auftrag ein. Unser kompetentes Berater- und Technikerteam zeigt Dir, welche Methoden und Techniken sich in Abhängigkeit von den örtlichen und bautechnischen Besonderheiten des Veranstaltungsortes am besten in Dein Eventkonzept integrieren lassen.
				 */
				par2: string
				bullets: {
					/**
					 * LCD- und Plasmabildschirme
					 */
					'0': string
					/**
					 * Videokameras
					 */
					'1': string
					/**
					 * Video-Mischpulte und Interfaces
					 */
					'2': string
					/**
					 * Beamer und Prjektoren
					 */
					'3': string
				}
				/**
				 * Lass Deine Bilder für sich sprechen.
				 */
				quote: string
				/**
				 * /img/services/webp/video_card.webp
				 */
				img_card: string
				/**
				 * /img/services/webp/video_hero.webp
				 */
				img_hero: string
			}
			stage: {
				/**
				 * Bühnenbau
				 */
				title: string
				/**
				 * Wir sorgen für Deinen großen Auftritt!
				 */
				subtitle: string
				/**
				 * The stage is yours - der Mittelpunkt Deiner Inszenierung und das zentrale Element des gesamten Location- und Eventdesigns.
				 */
				teaser: string
				/**
				 * Die Bühne ist das zentrale Element des gesamten Location- und Eventdesigns. Ob Gala, Kongress oder Messe – überlass auch in puncto Bühnenbau nichts dem Zufall! Im Bereich Bühnen- und Messebau greift NEKO auf eine 10-jährige Erfahrung zurück, welche wir in zahlreichen Aufträgen für namhafte Firmen und Veranstalter sammeln durften. Diese Erfahrung lassen wir auch in Dein Projekt einfließen.
				 */
				par1: string
				/**
				 * Für Deinen Bühnen- und Messeauftritt haben wir das gesamte technische Equipment. Mal ist es nur das Licht, mal nur die Audio- oder Videoanlage, mal eine Aluminium- bzw. Traversenstruktur. Manchmal sind es aber auch alle Elemente zusammen. Neben der sorgfältigen Erstellung technisch optimaler Konstruktionen berücksichtigen wir auch optische Aspekte. Durch ansprechenden Dekorationsbau können beispielsweise technische Einrichtungen kinderleicht kaschiert werden. Damit verbinden wir zwei wesentliche Anforderungen: Sicherheit und Ästhetik.
				 */
				par2: string
				bullets: {
					/**
					 * Bühnenpodeste
					 */
					'0': string
					/**
					 * Bühnenrückwände
					 */
					'1': string
					/**
					 * Trennvorhänge
					 */
					'2': string
					/**
					 * Truss Systeme
					 */
					'3': string
					/**
					 * Planung und Aufbau
					 */
					'4': string
				}
				/**
				 * Lass Dich mit einem Bühnenkonzept perfekt in Szene setzen.
				 */
				quote: string
				/**
				 * /img/services/webp/stage_card.webp
				 */
				img_card: string
				/**
				 * /img/services/webp/stage_hero.webp
				 */
				img_hero: string
			}
			presentation: {
				/**
				 * Präsentationstechnik
				 */
				title: string
				/**
				 * Wir verschaffen Dir Aufmerksamkeit!
				 */
				subtitle: string
				/**
				 * Bei Produktpräsentationen, Seminaren und Tagungen ist multimediale Kommunikation auf höchstem Niveau gefragt.
				 */
				teaser: string
				/**
				 * Produktpräsentationen, Seminare und Tagungen stellen eine besondere Herausforderung dar. Hier ist multimediale Kommunikation auf höchstem Niveau gefragt. Unser Expertenteam sorgt für optimale Akustik und ein gestochen scharfes Bild. Gemeinsam finden wir maßgeschneiderte Lösungen für Dein ganz persönliches Business-Programm und eine gelungene, störungsfreie Konferenz.
				 */
				par1: string
				/**
				 * Es spielt keine Rolle in welchen Dimensionen Deine Tagung geplant ist. NEKO hat für alle Belange das passende Equipment und die Kompetenz, alle Komponenten einzurichten und aufeinander abzustimmen. Unsere Produktpalette besteht ausschließlich aus modernster Technik. So werden Deine Botschaften besonders wirksam und finden Anklang bei allen Zuschauern.
				 */
				par2: string
				bullets: {
					/**
					 * Beamer und Leinwände
					 */
					'0': string
					/**
					 * LED-Wände und Bildschirme
					 */
					'1': string
					/**
					 * Videokonferenzsysteme
					 */
					'2': string
					/**
					 * Audiotechnik
					 */
					'3': string
					/**
					 * Befestigungssysteme
					 */
					'4': string
				}
				/**
				 * Unser Know-how und Hingabe – Dein erfolgreicher Auftritt!
				 */
				quote: string
				/**
				 * /img/services/webp/presentation_card.webp
				 */
				img_card: string
				/**
				 * /img/services/webp/presentation_hero.webp
				 */
				img_hero: string
			}
			service: {
				/**
				 * Service & Reparatur
				 */
				title: string
				/**
				 * Wir sind für Dich da.
				 */
				subtitle: string
				/**
				 * Von individuellen Reparatur- und Wartungsleistungen bis zum Service auf Abruf mit kurzen Reaktionszeiten.
				 */
				teaser: string
				/**
				 * Ganz egal was Du vorhast: Wir sind da, wenn Du uns brauchst. Vom Briefing, über die Konzeption und Durchführung des Events, bis hin zur Wartung und Installation von Equipment. In enger Zusammenarbeit eruieren wir den Umfang Deines Vorhabens und prüfen den Auftrag auf technische Umsetzbarkeit sowie Budgetvorstellung. Bei der Konzeption greifen wir voll und ganz auf unsere jahrelange Erfahrung im Bereich des Veranstaltungsmanagements zurück.
				 */
				par1: string
				/**
				 * Aus Deinen Vorgaben und unserem Know-how entsteht ein persönliches, einzigartiges Konzept und ein präziser Aufbau- und Ablaufplan der Veranstaltung. Daraufhin erwecken wir diesen Plan bis zum letzten Detail zum Leben. Doch damit ist unsere Arbeit noch nicht getan: Individuelle Reparatur- und Wartungsleistungen und kurzfristiger Service auf Abruf sind bei uns standart. Die Sicherheit der Beteiligten und die Makellosigkeit des Equipments sind das A und O eines gelungenen Events. Auf Wunsch bieten wir einen Techniker-Notdienst sowie einen Hotline-Support an.
				 */
				par2: string
				bullets: {
					/**
					 * Briefing und Konzepterstellung
					 */
					'0': string
					/**
					 * Erstellung eines Event-Ablaufplans
					 */
					'1': string
					/**
					 * Aufbau und Installation
					 */
					'2': string
					/**
					 * Hotline-Support
					 */
					'3': string
					/**
					 * Techniker-Notdienst
					 */
					'4': string
					/**
					 * Reparatur und Wartung
					 */
					'5': string
				}
				/**
				 * Dein Erfolg ist für uns das Wichtigste!
				 */
				quote: string
				/**
				 * /img/services/webp/service_card.webp
				 */
				img_card: string
				/**
				 * /img/services/webp/service_hero.webp
				 */
				img_hero: string
			}
		}
	}
	contact: {
		/**
		 * Kontakt
		 */
		title: string
		/**
		 * Schreib uns.
		 */
		heading: string
		/**
		 * Hinterlasse eine Nachticht mit Deinem Anliegen. Wir melden uns so schnell wie möglich, versprochen! Alternativ kannst Du auch direkt mit uns chatten.
		 */
		subheading: string
		form: {
			/**
			 * Name
			 */
			name: string
			/**
			 * Die Eingabe muss mindestens 2 Zeichen enthalten. Nur Buchstaben sowie "-" und  "." erlaubt.
			 */
			name_error: string
			/**
			 * E-Mail
			 */
			email: string
			/**
			 * Tel (optional)
			 */
			tel: string
			/**
			 * Die Eingabe muss mindestens 4 Zeichen enthalten. Nur Zahlen und "+" erlaubt.
			 */
			tel_error: string
			/**
			 * Nachricht
			 */
			message: string
			/**
			 * Ich stimme der Verarbeitung meiner Daten zum Zweck der Kontaktaufnahme durch die NEKO Music & Media GmbH zu und akzeptiere den Datenschutz.
			 */
			privacy: string
			/**
			 * Abschicken!
			 */
			send_button: string
			success_message: {
				/**
				 * Nachricht erfolgreich versendet!
				 */
				heading: string
				/**
				 * Wir melden uns so schnell wie möglich.
				 */
				subheading: string
			}
			failure_message: {
				/**
				 * Nachricht konnte nicht versendet werden!
				 */
				heading: string
				/**
				 * Bitte kontaktiere uns unter <a class="underline" href="mailto:info@nekomusicmedia.de">info@nekomusicmedia.de</a>.
				 */
				subheading: string
			}
		}
		contact_data: {
			/**
			 * Finde den Weg zu uns.
			 */
			heading: string
			/**
			 * Besuche uns in unserem Büro/Showroom in Mönchengladbach. Parkplätze vorhanden.
			 */
			subheading: string
			/**
			 * Neko Music & Media GmbH
						Adolf-Kempken-Weg 95-99
						41189 Mönchengladbach
						tel: <a href="tel:004921662784507">+49 2166 2784507</a>
						fax: <a href="tel:004921662784509">+49 2166 2784509</a>
						mail: <a href="mailto:info@neko-music-media.de">info@nekomusicmedia.de</a>
			 */
			address: string
		}
	}
	footer: {
		/**
		 * Auf Social Media unterwegs?
		 */
		social_media_heading: string
		/**
		 * Kontaktiere uns auf folgenden Plattformen.
		 */
		social_media_subheading: string
		/**
		 * Links
		 */
		links: string
		/**
		 * Alle Leistungen
		 */
		all_services: string
		/**
		 * Copyright © {year} NEKO Music & Media GmbH
		 * @param {number} year
		 */
		copyright: RequiredParams<'year'>
	}
}

export type TranslationFunctions = {
	/**
	 * Jetzt kontaktieren
	 */
	contact_button: () => LocalizedString
	/**
	 * kostenlos Angebot anfordern
	 */
	contact_button_offer: () => LocalizedString
	index: {
		/**
		 * Startseite
		 */
		title: () => LocalizedString
		/**
		 * Dein Auftrag ist unser Antrieb!
		 */
		heading: () => LocalizedString
		/**
		 * NEKO ist Dein kompetenter und zuverlässiger Full-Service-Partner im Bereich Veranstaltungstechnik und -management.
		 */
		subheading: () => LocalizedString
		/**
		 * /img/index/webp/hero.webp
		 */
		img_hero: () => LocalizedString
		examples: {
			events: {
				/**
				 * Events
				 */
				title: () => LocalizedString
				/**
				 * Jede Veranstaltung ist einmalig
				 */
				subtitle: () => LocalizedString
				/**
				 * NEKO stattet Dein Event mit qualitativer und fortschrittlicher Technik aus. Durch exzellente Beratung, fachgerechte Planung sowie professionelle Umsetzung sorgen wir dafür, dass Deine Veranstaltung unvergesslich wird!
				 */
				text: () => LocalizedString
				/**
				 * /img/index/webp/events.webp
				 */
				img: () => LocalizedString
			}
			exhibitions: {
				/**
				 * Messen & Aussteller
				 */
				title: () => LocalizedString
				/**
				 * Überlass nichts dem Zufall
				 */
				subtitle: () => LocalizedString
				/**
				 * Wir meistern alle technischen und logistischen Herausforderungen Deines Messeauftritts. Mit Ideenreichtum und jahrelanger Erfahrung im Messe- und Standbau sorgen wir für individuelle und einmalige Messepräsenz.
				 */
				text: () => LocalizedString
				/**
				 * /img/index/webp/exhibitions.webp
				 */
				img: () => LocalizedString
			}
			seminars: {
				/**
				 * Kongresse & Seminare
				 */
				title: () => LocalizedString
				/**
				 * Im großen oder kleinen Stil
				 */
				subtitle: () => LocalizedString
				/**
				 * Mit modernster Konferenz- und Medientechnik und unserem Full-Service-Ansatz übernehmen wir die Konzeption Deines Business-Programms und sorgen für einen reibungslosen Ablauf.
				 */
				text: () => LocalizedString
				/**
				 * /img/index/webp/seminars.webp
				 */
				img: () => LocalizedString
			}
			hotels: {
				/**
				 * Hotels
				 */
				title: () => LocalizedString
				/**
				 * Event- und Treffpunkt
				 */
				subtitle: () => LocalizedString
				/**
				 * Ob Geschäftsmeeting, Hochzeit oder privates Fest – mit unserem Know-how beraten wir Dich bei der Auswahl des richtigen Veranstaltungsequipments und setzen Dein Hotel-Event perfekt ins Szene.
				 */
				text: () => LocalizedString
				/**
				 * /img/index/webp/hotels.webp
				 */
				img: () => LocalizedString
			}
		}
	}
	about: {
		/**
		 * Über uns
		 */
		title: () => LocalizedString
		/**
		 * Erfahren. Persönlich. Vielseitig. Servicestark.
		 */
		heading: () => LocalizedString
		/**
		 * Unsere Leitsätze für Deinen Erfolg!
		 */
		subheading: () => LocalizedString
		/**
		 * /img/about/webp/hero.webp
		 */
		img_hero: () => LocalizedString
		texts: {
			experienced: {
				/**
				 * Erfahren.
				 */
				title: () => LocalizedString
				/**
				 * Seit mehr als 10 Jahren gestalten und inszenieren wir unvergessliche Events und Veranstaltungen mit professionellem Equipment und solidem Know-how.
				 */
				text_card: () => LocalizedString
				/**
				 * NEKO versteht sich als technischer Allround-Dienstleister mit individuellen Lösungsansätzen in den Segmenten Ton-, Licht-, Video-, Präsentationstechnik sowie Bühnenbau. Wir bieten eine breitgefächerte Palette an Equipment und Service für Veranstaltungen jeder Dimension an.
				 */
				text: () => LocalizedString
				/**
				 * /img/about/webp/experienced.webp
				 */
				img: () => LocalizedString
			}
			personal: {
				/**
				 * Persönlich.
				 */
				title: () => LocalizedString
				/**
				 * Gerne empfangen wir Dich zu einem unverbindlichen Gespräch in unserem Showroom in Mönchengladbach, wo Du Dich vom professionellen Equipment aus hauseigenem Technikbestand überzeugen kannst.
				 */
				text_card: () => LocalizedString
				/**
				 * Ob Du auf einzelne Bereiche der Eventtechnik zurückgreifen möchtest, den ganzheitlichen Allround-Ansatz bevorzugst oder Dein eigenes Equipment in Reparatur geben möchtest – nimm jetzt unverbindlich Kontakt mit uns auf.
				 */
				text: () => LocalizedString
				/**
				 * /img/about/webp/personal.webp
				 */
				img: () => LocalizedString
			}
			diverse: {
				/**
				 * Vielfältig.
				 */
				title: () => LocalizedString
				/**
				 * Konzert, Gala, Tagung, Konferenz, Präsentation oder Messeauftritt. Was steht als nächstes auf Deiner Agenda? Als Partner haben wir unsere Leistungspalette an die allseitigen Herausforderungen unterschiedlichster Szenarien angepasst.
				 */
				text_card: () => LocalizedString
				/**
				 * Mit unserem professionellen Netzwerk aus Kooperationspartnern planen und realisieren wir lokale und internationale Events. Dabei geben wir uns mit 08/15-Lösungen genauso wenig zufrieden wie unsere Kunden. Aus Deinen Ideen und Vorstellungen kreieren wir innovative, maßgeschneiderte Konzepte und inszenieren stimmungsvolle, unvergessliche Events.
				 */
				text: () => LocalizedString
				/**
				 * /img/about/webp/diverse.webp
				 */
				img: () => LocalizedString
			}
			servicestrong: {
				/**
				 * Servicestark.
				 */
				title: () => LocalizedString
				/**
				 * Bei uns bekommst Du nicht nur hochwertiges Equipment, sondern auf Wunsch auch Beratungs- und Serviceleistungen wie Unterstützung bei der Eventplanunglanung, Aufbau, Installation, Reparatur und vieles mehr.
				 */
				text_card: () => LocalizedString
				/**
				 * Unser Team aus Toningeneuren, Informatikern, Bühnen- & Veranstaltungstechnikern, Licht- & Videooperatoren, Technischen Planern und Bühnenhelfern berät Dich bei sämtlichen Herausforderungen. Stets kompetent, budgetorientiert und technisch versiert! Ob regional oder international, groß oder klein – Dein Auftrag ist unser Antrieb!
				 */
				text: () => LocalizedString
				/**
				 * /img/about/webp/servicestrong.webp
				 */
				img: () => LocalizedString
			}
		}
	}
	services: {
		/**
		 * Leistungen
		 */
		title: () => LocalizedString
		/**
		 * mehr erfahren
		 */
		more_button: () => LocalizedString
		/**
		 * Produktpalette
		 */
		products_title: () => LocalizedString
		all: {
			sound: {
				/**
				 * Tontechnik
				 */
				title: () => LocalizedString
				/**
				 * Wir sorgen für guten Ton!
				 */
				subtitle: () => LocalizedString
				/**
				 * NEKO liefert optimale Beschallung, egal welche technischen Herausforderungen der Veranstaltungsort mit sich bringen mag.
				 */
				teaser: () => LocalizedString
				/**
				 * Ob Tagungen, Hotels oder Konzerthallen – die technischen und örtlichen Gegebenheiten sind in jeder Location unterschiedlich und beeinflussen die Klangqualität in entscheidendem Maße. Sauberer Klang ist eine unabdingbare Komponente für den Erfolg Deiner Veranstaltung. NEKO liefert die optimale Beschallung, egal welche Herausforderungen der Veranstaltungsort mit sich bringen mag.
				 */
				par1: () => LocalizedString
				/**
				 * Zusammen machen wir einen Plan und stellen Dir ausgezeichnetes Equipment von namhaften Herstellern zur Verfügung. Darüber hinaus installieren wir die Technik und führen die Veranstaltung fachlich versiert und Deinen Erwartungen entsprechend durch. Es kommen ausschließlich aufeinander abgestimmte Soundsysteme, moderne Mikrophone und leistungsfähige Peripheriegeräte zum Einsatz.
				 */
				par2: () => LocalizedString
				bullets: {
					/**
					 * Aktive und Passive Lautsprecher
					 */
					'0': () => LocalizedString
					/**
					 * Endstufen und Soundmanager
					 */
					'1': () => LocalizedString
					/**
					 * Kabel- und Funkmikrofone
					 */
					'2': () => LocalizedString
					/**
					 * Mischpulte und Monitore
					 */
					'3': () => LocalizedString
					/**
					 * DJ Technik
					 */
					'4': () => LocalizedString
				}
				/**
				 * Spüre mit uns die ganze Kraft des Klanges!
				 */
				quote: () => LocalizedString
				/**
				 * /img/services/webp/sound_card.webp
				 */
				img_card: () => LocalizedString
				/**
				 * /img/services/webp/sound_hero.webp
				 */
				img_hero: () => LocalizedString
			}
			light: {
				/**
				 * Lichttechnik
				 */
				title: () => LocalizedString
				/**
				 * Wir bringen Licht ins Dunkel!
				 */
				subtitle: () => LocalizedString
				/**
				 * Bewegtes Licht, LED oder beides? Bühne, Show oder Messestand? Licht ist Pflicht!
				 */
				teaser: () => LocalizedString
				/**
				 * Bewegtes Licht, LED oder beides? Bühne, Show oder Messestand? Eins steht fest: Licht ist Pflicht und Du hast die Wahl! NEKO hat einen außergewöhnlich breiten Lichttechnik-Park, der keinen Deiner Wünsche offen lässt. Verzaubere Dein Publikum und profitiere von modernen, spektakulären Lichteffekten.
				 */
				par1: () => LocalizedString
				/**
				 * Keine Komponente der Veranstaltungstechnik berührt so sehr wie das Lichtdesign. Es ist ein Gestaltungsmittel, welches Räume in eine beeindruckende Atmosphäre rückt und wirkungsvolle Stimmungen erzeugt. Unsere Lichtdesigner wissen, wie man dieses Mittel gekonnt einsetzt und entwickeln ein überzeugendes Lichtkonzept, das Deinen Räumen Charakter verleiht. Wir beraten Dich bei der Auswahl und bieten Dir Dein ganz individuelles Lichtspektakel.
				 */
				par2: () => LocalizedString
				bullets: {
					/**
					 * Kunst- und Tageslichtscheinwerfer
					 */
					'0': () => LocalizedString
					/**
					 * LED Scheinwerfer und LED Panels
					 */
					'1': () => LocalizedString
					/**
					 * Movinglights und Followspots
					 */
					'2': () => LocalizedString
					/**
					 * Profilscheinwerfer und Outdoorstrahler
					 */
					'3': () => LocalizedString
					/**
					 * Farbwechsler und Nebelgeräte
					 */
					'4': () => LocalizedString
					/**
					 * Lichtsteuerungen, Dimmer und Switches
					 */
					'5': () => LocalizedString
					/**
					 * Stromverteilungen und -generatoren
					 */
					'6': () => LocalizedString
					/**
					 * Traversen und Lichtstative
					 */
					'7': () => LocalizedString
				}
				/**
				 * Erst ein gekonnt inszeniertes Lichtdesign macht aus Deinem Event ein Highlight.
				 */
				quote: () => LocalizedString
				/**
				 * /img/services/webp/light_card.webp
				 */
				img_card: () => LocalizedString
				/**
				 * /img/services/webp/light_hero.webp
				 */
				img_hero: () => LocalizedString
			}
			video: {
				/**
				 * Videotechnik
				 */
				title: () => LocalizedString
				/**
				 * Wir bringen Deine Bilder in Bewegung!
				 */
				subtitle: () => LocalizedString
				/**
				 * Animationen, Imagefilme, Präsentationscharts oder Grafiken - mit uns gibst Du immer ein gutes Bild ab.
				 */
				teaser: () => LocalizedString
				/**
				 * Durch ein reibungsloses Zusammenspiel von Bild und Ton hinterlässt Du bei Deinen Zuschauern einen bleibenden Eindruck. Eine visuelle Untermalung verleiht dem Gesagten mehr Ausdruck, fokussiert die Sinne der Zuschauer auf die Kernbotschaften des Vortrags und hebt diese eindrucksvoll und nachhaltig hervor.
				 */
				par1: () => LocalizedString
				/**
				 * Wir bringen unsere ganze Erfahrung mit der medientechnischen Umsetzung von Vorträgen, Reportagen und Live-Übertragungen in Deinen Auftrag ein. Unser kompetentes Berater- und Technikerteam zeigt Dir, welche Methoden und Techniken sich in Abhängigkeit von den örtlichen und bautechnischen Besonderheiten des Veranstaltungsortes am besten in Dein Eventkonzept integrieren lassen.
				 */
				par2: () => LocalizedString
				bullets: {
					/**
					 * LCD- und Plasmabildschirme
					 */
					'0': () => LocalizedString
					/**
					 * Videokameras
					 */
					'1': () => LocalizedString
					/**
					 * Video-Mischpulte und Interfaces
					 */
					'2': () => LocalizedString
					/**
					 * Beamer und Prjektoren
					 */
					'3': () => LocalizedString
				}
				/**
				 * Lass Deine Bilder für sich sprechen.
				 */
				quote: () => LocalizedString
				/**
				 * /img/services/webp/video_card.webp
				 */
				img_card: () => LocalizedString
				/**
				 * /img/services/webp/video_hero.webp
				 */
				img_hero: () => LocalizedString
			}
			stage: {
				/**
				 * Bühnenbau
				 */
				title: () => LocalizedString
				/**
				 * Wir sorgen für Deinen großen Auftritt!
				 */
				subtitle: () => LocalizedString
				/**
				 * The stage is yours - der Mittelpunkt Deiner Inszenierung und das zentrale Element des gesamten Location- und Eventdesigns.
				 */
				teaser: () => LocalizedString
				/**
				 * Die Bühne ist das zentrale Element des gesamten Location- und Eventdesigns. Ob Gala, Kongress oder Messe – überlass auch in puncto Bühnenbau nichts dem Zufall! Im Bereich Bühnen- und Messebau greift NEKO auf eine 10-jährige Erfahrung zurück, welche wir in zahlreichen Aufträgen für namhafte Firmen und Veranstalter sammeln durften. Diese Erfahrung lassen wir auch in Dein Projekt einfließen.
				 */
				par1: () => LocalizedString
				/**
				 * Für Deinen Bühnen- und Messeauftritt haben wir das gesamte technische Equipment. Mal ist es nur das Licht, mal nur die Audio- oder Videoanlage, mal eine Aluminium- bzw. Traversenstruktur. Manchmal sind es aber auch alle Elemente zusammen. Neben der sorgfältigen Erstellung technisch optimaler Konstruktionen berücksichtigen wir auch optische Aspekte. Durch ansprechenden Dekorationsbau können beispielsweise technische Einrichtungen kinderleicht kaschiert werden. Damit verbinden wir zwei wesentliche Anforderungen: Sicherheit und Ästhetik.
				 */
				par2: () => LocalizedString
				bullets: {
					/**
					 * Bühnenpodeste
					 */
					'0': () => LocalizedString
					/**
					 * Bühnenrückwände
					 */
					'1': () => LocalizedString
					/**
					 * Trennvorhänge
					 */
					'2': () => LocalizedString
					/**
					 * Truss Systeme
					 */
					'3': () => LocalizedString
					/**
					 * Planung und Aufbau
					 */
					'4': () => LocalizedString
				}
				/**
				 * Lass Dich mit einem Bühnenkonzept perfekt in Szene setzen.
				 */
				quote: () => LocalizedString
				/**
				 * /img/services/webp/stage_card.webp
				 */
				img_card: () => LocalizedString
				/**
				 * /img/services/webp/stage_hero.webp
				 */
				img_hero: () => LocalizedString
			}
			presentation: {
				/**
				 * Präsentationstechnik
				 */
				title: () => LocalizedString
				/**
				 * Wir verschaffen Dir Aufmerksamkeit!
				 */
				subtitle: () => LocalizedString
				/**
				 * Bei Produktpräsentationen, Seminaren und Tagungen ist multimediale Kommunikation auf höchstem Niveau gefragt.
				 */
				teaser: () => LocalizedString
				/**
				 * Produktpräsentationen, Seminare und Tagungen stellen eine besondere Herausforderung dar. Hier ist multimediale Kommunikation auf höchstem Niveau gefragt. Unser Expertenteam sorgt für optimale Akustik und ein gestochen scharfes Bild. Gemeinsam finden wir maßgeschneiderte Lösungen für Dein ganz persönliches Business-Programm und eine gelungene, störungsfreie Konferenz.
				 */
				par1: () => LocalizedString
				/**
				 * Es spielt keine Rolle in welchen Dimensionen Deine Tagung geplant ist. NEKO hat für alle Belange das passende Equipment und die Kompetenz, alle Komponenten einzurichten und aufeinander abzustimmen. Unsere Produktpalette besteht ausschließlich aus modernster Technik. So werden Deine Botschaften besonders wirksam und finden Anklang bei allen Zuschauern.
				 */
				par2: () => LocalizedString
				bullets: {
					/**
					 * Beamer und Leinwände
					 */
					'0': () => LocalizedString
					/**
					 * LED-Wände und Bildschirme
					 */
					'1': () => LocalizedString
					/**
					 * Videokonferenzsysteme
					 */
					'2': () => LocalizedString
					/**
					 * Audiotechnik
					 */
					'3': () => LocalizedString
					/**
					 * Befestigungssysteme
					 */
					'4': () => LocalizedString
				}
				/**
				 * Unser Know-how und Hingabe – Dein erfolgreicher Auftritt!
				 */
				quote: () => LocalizedString
				/**
				 * /img/services/webp/presentation_card.webp
				 */
				img_card: () => LocalizedString
				/**
				 * /img/services/webp/presentation_hero.webp
				 */
				img_hero: () => LocalizedString
			}
			service: {
				/**
				 * Service & Reparatur
				 */
				title: () => LocalizedString
				/**
				 * Wir sind für Dich da.
				 */
				subtitle: () => LocalizedString
				/**
				 * Von individuellen Reparatur- und Wartungsleistungen bis zum Service auf Abruf mit kurzen Reaktionszeiten.
				 */
				teaser: () => LocalizedString
				/**
				 * Ganz egal was Du vorhast: Wir sind da, wenn Du uns brauchst. Vom Briefing, über die Konzeption und Durchführung des Events, bis hin zur Wartung und Installation von Equipment. In enger Zusammenarbeit eruieren wir den Umfang Deines Vorhabens und prüfen den Auftrag auf technische Umsetzbarkeit sowie Budgetvorstellung. Bei der Konzeption greifen wir voll und ganz auf unsere jahrelange Erfahrung im Bereich des Veranstaltungsmanagements zurück.
				 */
				par1: () => LocalizedString
				/**
				 * Aus Deinen Vorgaben und unserem Know-how entsteht ein persönliches, einzigartiges Konzept und ein präziser Aufbau- und Ablaufplan der Veranstaltung. Daraufhin erwecken wir diesen Plan bis zum letzten Detail zum Leben. Doch damit ist unsere Arbeit noch nicht getan: Individuelle Reparatur- und Wartungsleistungen und kurzfristiger Service auf Abruf sind bei uns standart. Die Sicherheit der Beteiligten und die Makellosigkeit des Equipments sind das A und O eines gelungenen Events. Auf Wunsch bieten wir einen Techniker-Notdienst sowie einen Hotline-Support an.
				 */
				par2: () => LocalizedString
				bullets: {
					/**
					 * Briefing und Konzepterstellung
					 */
					'0': () => LocalizedString
					/**
					 * Erstellung eines Event-Ablaufplans
					 */
					'1': () => LocalizedString
					/**
					 * Aufbau und Installation
					 */
					'2': () => LocalizedString
					/**
					 * Hotline-Support
					 */
					'3': () => LocalizedString
					/**
					 * Techniker-Notdienst
					 */
					'4': () => LocalizedString
					/**
					 * Reparatur und Wartung
					 */
					'5': () => LocalizedString
				}
				/**
				 * Dein Erfolg ist für uns das Wichtigste!
				 */
				quote: () => LocalizedString
				/**
				 * /img/services/webp/service_card.webp
				 */
				img_card: () => LocalizedString
				/**
				 * /img/services/webp/service_hero.webp
				 */
				img_hero: () => LocalizedString
			}
		}
	}
	contact: {
		/**
		 * Kontakt
		 */
		title: () => LocalizedString
		/**
		 * Schreib uns.
		 */
		heading: () => LocalizedString
		/**
		 * Hinterlasse eine Nachticht mit Deinem Anliegen. Wir melden uns so schnell wie möglich, versprochen! Alternativ kannst Du auch direkt mit uns chatten.
		 */
		subheading: () => LocalizedString
		form: {
			/**
			 * Name
			 */
			name: () => LocalizedString
			/**
			 * Die Eingabe muss mindestens 2 Zeichen enthalten. Nur Buchstaben sowie "-" und  "." erlaubt.
			 */
			name_error: () => LocalizedString
			/**
			 * E-Mail
			 */
			email: () => LocalizedString
			/**
			 * Tel (optional)
			 */
			tel: () => LocalizedString
			/**
			 * Die Eingabe muss mindestens 4 Zeichen enthalten. Nur Zahlen und "+" erlaubt.
			 */
			tel_error: () => LocalizedString
			/**
			 * Nachricht
			 */
			message: () => LocalizedString
			/**
			 * Ich stimme der Verarbeitung meiner Daten zum Zweck der Kontaktaufnahme durch die NEKO Music & Media GmbH zu und akzeptiere den Datenschutz.
			 */
			privacy: () => LocalizedString
			/**
			 * Abschicken!
			 */
			send_button: () => LocalizedString
			success_message: {
				/**
				 * Nachricht erfolgreich versendet!
				 */
				heading: () => LocalizedString
				/**
				 * Wir melden uns so schnell wie möglich.
				 */
				subheading: () => LocalizedString
			}
			failure_message: {
				/**
				 * Nachricht konnte nicht versendet werden!
				 */
				heading: () => LocalizedString
				/**
				 * Bitte kontaktiere uns unter <a class="underline" href="mailto:info@nekomusicmedia.de">info@nekomusicmedia.de</a>.
				 */
				subheading: () => LocalizedString
			}
		}
		contact_data: {
			/**
			 * Finde den Weg zu uns.
			 */
			heading: () => LocalizedString
			/**
			 * Besuche uns in unserem Büro/Showroom in Mönchengladbach. Parkplätze vorhanden.
			 */
			subheading: () => LocalizedString
			/**
			 * Neko Music & Media GmbH
						Adolf-Kempken-Weg 95-99
						41189 Mönchengladbach
						tel: <a href="tel:004921662784507">+49 2166 2784507</a>
						fax: <a href="tel:004921662784509">+49 2166 2784509</a>
						mail: <a href="mailto:info@neko-music-media.de">info@nekomusicmedia.de</a>
			 */
			address: () => LocalizedString
		}
	}
	footer: {
		/**
		 * Auf Social Media unterwegs?
		 */
		social_media_heading: () => LocalizedString
		/**
		 * Kontaktiere uns auf folgenden Plattformen.
		 */
		social_media_subheading: () => LocalizedString
		/**
		 * Links
		 */
		links: () => LocalizedString
		/**
		 * Alle Leistungen
		 */
		all_services: () => LocalizedString
		/**
		 * Copyright © {year} NEKO Music & Media GmbH
		 */
		copyright: (arg: { year: number }) => LocalizedString
	}
}

export type Formatters = {}
